spring:
  application:
    name: lms-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db?options=-c%20timezone=Asia/Kolkata
    username: lms_user
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway manages schema, not Hibernate
    show-sql: true                # print every SQL query in console
    properties:
      hibernate:
        format_sql: true          # make SQL readable in console

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: akashbajeri18@gmail.com
    password: jadd kqxm vwbv pbor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 30s

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: lms-transcoding-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.lms.*"

server:
  port: 8080

logging:
  level:
    com.lms: DEBUG                # see all your own code's logs
    org.springframework.security: DEBUG   # see security decisions

application:                      # Root application key
  security:
    jwt:
      secret-key: 3f8a9b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0
      access-token-expiration: 900000        # 15 minutes in ms
      refresh-token-expiration: 604800000    # 7 days in ms
  mail:
    from: akashbajeri18@gmail.com
    from-name: LMS Platform

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha

razorpay:
  key-id: rzp_test_SuQJvcU5v8A9Fy
  key-secret: Lo8Cau0BFPZRHH5SVRc5vGyo
  currency: INR

aws:
  s3:
    endpoint: http://localhost:4566    # LocalStack endpoint
    region: us-east-1
    bucket-name: lms-media-bucket
    access-key: test                   # LocalStack accepts any value
    secret-key: test                   # LocalStack accepts any value
    presigned-url-expiry: 60           # in seconds
